using Robust.Client;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Editor;

[GenerateTypedNameReferences]
public sealed partial class GameEditorView : BoxContainer
{
    public GameEditorView()
    {
        RobustXamlLoader.Load(this);
        Viewport.ViewportSize = new Vector2i(512, 512);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(Layout, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(Viewport, LayoutContainer.LayoutPreset.Wide);
        Viewport.SetPositionFirst();
        
        EditorMenuBar.Menus.Add(new MenuBar.Menu()
        {
            Title = "File",
            Entries = {
                new MenuBar.MenuButton()
                {
                    Text = "Open"
                },
                new MenuBar.MenuButton()
                {
                    Text = "Save",
                },
                new MenuBar.MenuButton()
                {
                    Text = "Save As",
                },
                new MenuBar.MenuSeparator(),
                new MenuBar.MenuButton()
                {
                    Text = "Exit",
                }
            }
        });
        
        EditorMenuBar.Menus.Add(new MenuBar.Menu()
        {
            Title = "Edit",
        });
        
        EditorMenuBar.Menus.Add(new MenuBar.Menu()
        {
            Title = "View",
        });
        
        EditorMenuBar.Menus.Add(new MenuBar.Menu()
        {
            Title = "Test",
        });
    }
}