using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Editor;

[GenerateTypedNameReferences]
public partial class GameEditorView : BoxContainer
{
    
}